### ISSUE TITLE
Create release for us corporate users?

### ISSUE THREAD

**Issue by octol** [rollbear/lift#3]
Would it be possible to create a versioned release of the code as-is? It would make it much simpler for us stock in the corporate world who have to track our dependencies carefully

**Comment by rollbear** [comment]
That was a pleasant surprise. Yes, I can do this. There are a few things too many happening right this moment, but I can do this on Friday or during the weekend, if you're OK with waiting a couple of days.

**Comment by octol** [comment]
Absolutely, next week is fine!

**Comment by rollbear** [comment]
Just tagged release v1. No code changes, but added ChangeLog (no history yet,) and a short depressing compiler compatibility blurb. I notice I need to write a couple of compiller bug reports ;-)
