### ISSUE TITLE
[nitpick] Negating 'std::less' should give you 'greater than or equal to' not 'greater than'.

### ISSUE THREAD

**Issue by bostikforever** [rollbear/lift#5]
https://github.com/rollbear/lift/blame/master/README.md#L182 names the result of negating 'std::less' 'binary_gt'. The suffix 'gt' seems to suggest 'greater than'.

**Comment by rollbear** [comment]
Yes, you're right. Thanks. If you want to, you can send a pull request with the fix, otherwise I'll correct it tonight.

**Comment by rollbear** [comment]
Fixed in commit 42293d66f0bd5a92b2a0ab42284e56950d56d853
